---

- hosts: all
  become: true
  tasks:

  - name: install apache and php packages for Ubuntu
    apt:
      name: 
      - apache2
      - libapache2-mod-php
      state: latest
      update_cache: yes
      when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install apache and php packages for Rocky Linux
    apt:
      name:
      - httpd
      - php
      state: latest
      update_cache: yes
      when: ansible_distribution in ["Rocky", "CentOS"]
