---

- hosts: all
  become: true
  tasks:

  - name: update repository 
    apt:
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: update repository
    dnf:
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: install apache2 package
    dnf:
      name: httpd.x86_64
      state: latest
    when: ansible_distribution == "Rocky"

  - name: add php support for apache
    dnf:
      name: php.x86_64
      state: latest
    when: ansible_distribution == "Rocky"
