---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Rocky,CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ["Rocky", "CentOS"]

  - name: install updates (Debian/Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php packages for Ubuntu
    tags: apache, apache2, ubuntu
    apt:
      name: 
      - apache2
      - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install apache and php packages for Rocky Linux
    tags: apache, rocky, httpd
    dnf:
      name:
      - httpd
      - php
      state: latest
    when: ansible_distribution in ["Rocky", "CentOS"]

- hosts: db_servers
  become: true
  tasks:

  - name: install httpd package (Rocky/CentOS)
    tags: rocky,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution in ["Rocky", "CentOS"]

  - name: install mariadb server
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: file_servers
  become: true
  tasks:
  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest

