---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (Rocky,CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ["Rocky", "CentOS"]

  - name: update repo cache (Debian/Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: all
  become: true
  tasks:

  - name: add ssh key for gunter
    tags: always
    authorized_key:
      user: gunter
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH0EDH7IXJs3TNE4ZGieKRIiGE6aCCk6e04922uatHDd root@Ansible"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php packages for Ubuntu
    tags: apache, apache2, ubuntu
    apt:
      name: 
      - apache2
      - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install apache and php packages for Rocky Linux
    tags: apache, rocky, httpd
    dnf:
      name:
      - httpd
      - php
      state: latest
    when: ansible_distribution in ["Rocky", "CentOS"]

  - name: start httpd (Rocky)
    tags: httpd, apache, Rocky
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution in ["Rocky", "CentOS"]

  - name: change e-mail address for admin
    tags:  httpd, apache, Rocky
    lineinfile: 
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line:  ServerAdmin somebody@somewhere.net
    when: ansible_distribution in ["Rocky", "CentOS"]
    register: httpd

  - name: copy deault html file for site
    tags:  apache, apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install httpd package (Rocky/CentOS)
    tags: rocky,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution in ["Rocky", "CentOS"]

  - name: install mariadb server
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: file_servers
  become: true
  tasks:
  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
