- name: install apache and php packages
  tags: apache, apache2, httpd,  php
  package:
    name:
    - "{{ apache_package_name }}"
    - "{{ php_package_name }}"
    state: latest

- name: start and enable apache service 
  tags: httpd, apache
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: change e-mail address for admin
  tags:  httpd, apache, rocky, centos
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line:  ServerAdmin somebody@somewhere.com
  when: ansible_distribution in ["Rocky", "CentOS"]
  notify: restart_apache

- name: copy deault html file for site
  tags:  apache, httpd, rocky, ubuntu
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: Write a PHP script as default page
  tags:  apache,httpd
  blockinfile:
    path:  /var/www/html/index.php
    create: yes
    marker: ""
    block: |
      <h1>Greetings from <?php print gethostname(); ?>
      <br>
      <?php phpinfo(); ?>
      <br>
    marker_end: ""
    owner: root
    group: root
    mode: 0644
