- name: install apache and php packages for Ubuntu
  tags: apache, apache2, ubuntu
  apt:
    name:
    - apache2
    - libapache2-mod-php
    state: latest
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: install apache and php packages for Rocky Linux
  tags: apache, rocky, httpd
  dnf:
    name:
    - httpd
    - php
    state: latest
  when: ansible_distribution in ["Rocky", "CentOS"]

- name: start httpd (Rocky)
  tags: httpd, apache, Rocky
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution in ["Rocky", "CentOS"]

- name: change e-mail address for admin
  tags:  httpd, apache, Rocky
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line:  ServerAdmin somebody@somewhere.net
  when: ansible_distribution in ["Rocky", "CentOS"]
  register: httpd

- name: copy deault html file for site
  tags:  apache, apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
