- name: install httpd package (Rocky/CentOS)
  tags: rocky,db,mariadb
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution in ["Rocky", "CentOS"]

- name: install mariadb server
  tags: db,mariadb,ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution in ["Debian", "Ubuntu"]
